kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.0
controlPlaneEndpoint: master
dns:
  type: CoreDNS
networking:
  dnsDomain: kubernetes.cluster
  serviceSubnet: 192.168.1.0/24
  podSubnet: 192.168.0.0/24
apiServer:
  extraArgs:
    advertise-address: 10.0.0.10
controllerManager:
  extraArgs:
    bind-address: 10.0.0.10
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
