apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool
spec:
  cidr: 192.168.0.0/24
  vxlanMode: Always                                 #################################################
  natOutgoing: true
  disabled: false
  nodeSelector: all()
