apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-vol
spec:
  storageClassName: nfs-mongo
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/nfs/storage/db"