apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nfs-mongo-vol
   namespace: labdb
spec:
  storageClassName: nfs-mongo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi