apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nuvym
  namespace: web
  labels:
    app: nginx-nuvym
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nuvym
  template:
    metadata:
      labels:
        app: nginx-nuvym
    spec:
      volumes: 
        - name: nfs-vol 
          persistentVolumeClaim:
            claimName: nfs-vol
      containers:
      - name: nginx-nuvym
        image: nginx:1.16
        ports:
        - containerPort: 80
        volumeMounts:
           - name: nfs-vol 
             mountPath: "/usr/share/nginx/html"
        startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 10  
        livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 10
            terminationGracePeriodSeconds: 0
        readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 5