apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-disk
spec:
  storageClassName: nfs-host
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/nfs/storage/web"